lint in github pr

diff --git a/.github/workflows/EVAL-deploy.yml b/.github/workflows/EVAL-deploy.yml
--- a/.github/workflows/EVAL-deploy.yml
+++ b/.github/workflows/EVAL-deploy.yml
@@ -1,4 +1,4 @@
-name: Build and deploy Furry Index (EVALUATION)
+name: Build and deploy (EVALUATION)
 
 on:
   push:
@@ -67,3 +67,33 @@ jobs:
 
             docker compose up -d
           EOF
+
+  health-check:
+    runs-on: ubuntu-latest
+
+    needs: remote-deploy
+
+    steps:
+      - name: Wait for response
+        run: |
+          URL="https://https://furry-index-eval.vmtech.services/api/whatisthisbuild"
+          max_attempts=30
+          attempt=1
+          interval=1
+  
+          while true; do
+            echo "Attempt $attempt / $max_attempts"
+            status=$(curl --silent --output /dev/null --write-out "%{http_code}" "$URL" || true)
+            if [ "$status" = "200" ]; then
+              echo "Remote service started succesfully."
+              break
+            fi
+  
+            if [ "$attempt" -ge "$max_attempts" ]; then
+              echo "Remote service returned error. Last status = $status"
+              exit 1
+            fi
+  
+            attempt=$(( attempt + 1 ))
+            sleep $interval
+          done
